name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: CMake build
        run: |
          cmake -S cpp -B build
          cmake --build build

      - name: Generate emoji data
        run: ./build/tdesktop-emoji-sprite-generator ../assets/emoji.txt ../web/data.txt 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: web
          retention-days: 90

  deploy:
    if: github.ref_name == 'master'
    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
